import type { FlowNode, FlowNodeType, FlowNodeTypeDefinition, FlowNodeCategory } from "../types";

export const NODE_CATEGORIES: { id: FlowNodeCategory; label: string; color: string }[] = [
  { id: "trigger", label: "Trigger", color: "#10b981" },
  { id: "content", label: "Contenuto", color: "#3b82f6" },
  { id: "interaction", label: "Interazione", color: "#8b5cf6" },
  { id: "conversion", label: "Conversione", color: "#f59e0b" },
  { id: "logic", label: "Logica", color: "#6366f1" },
  { id: "automation", label: "Automazione", color: "#ec4899" },
  { id: "exit", label: "Uscita", color: "#6b7280" },
];

export const FLOW_NODE_DEFINITIONS: Record<FlowNodeType, FlowNodeTypeDefinition> = {
  trigger: {
    type: "trigger",
    label: "Trigger Iniziale",
    description: "Punto di partenza del funnel",
    icon: "🚀",
    category: "trigger",
    color: "#d1fae5",
    borderColor: "#10b981",
    outputs: 1,
    isStartNode: true,
    defaultLabel: "Inizio",
    defaultConfig: () => ({ source: "ads", utm: {} }),
  },
  landing: {
    type: "landing",
    label: "Landing Page",
    description: "Pagina di atterraggio",
    icon: "🌐",
    category: "content",
    color: "#dbeafe",
    borderColor: "#3b82f6",
    outputs: 1,
    defaultLabel: "Landing Page",
    defaultConfig: () => ({ landingId: "", showHeader: true }),
  },
  quiz_start: {
    type: "quiz_start",
    label: "Inizio Quiz",
    description: "Avvio sequenza di domande",
    icon: "❓",
    category: "interaction",
    color: "#ede9fe",
    borderColor: "#8b5cf6",
    outputs: 1,
    defaultLabel: "Inizio Quiz",
    defaultConfig: () => ({ welcomeText: "Iniziamo!" }),
  },
  question: {
    type: "question",
    label: "Domanda",
    description: "Singola domanda con risposte",
    icon: "❔",
    category: "interaction",
    color: "#ede9fe",
    borderColor: "#8b5cf6",
    outputs: 4,
    defaultLabel: "Domanda",
    defaultConfig: () => ({
      questionText: "La tua domanda?",
      options: [
        { id: "opt1", label: "Sì", value: "si" },
        { id: "opt2", label: "No", value: "no" },
      ],
    }),
  },
  answer: {
    type: "answer",
    label: "Risposta",
    description: "Singola risposta utente",
    icon: "💬",
    category: "interaction",
    color: "#ede9fe",
    borderColor: "#8b5cf6",
    outputs: 1,
    defaultLabel: "Risposta",
    defaultConfig: () => ({ value: "" }),
  },
  form: {
    type: "form",
    label: "Modulo",
    description: "Modulo raccolta dati",
    icon: "📝",
    category: "conversion",
    color: "#fef3c7",
    borderColor: "#f59e0b",
    outputs: 1,
    defaultLabel: "Modulo",
    defaultConfig: () => ({ formId: "", required: ["firstName", "phone"] }),
  },
  booking: {
    type: "booking",
    label: "Prenotazione",
    description: "Calendario slot",
    icon: "📅",
    category: "conversion",
    color: "#fef3c7",
    borderColor: "#f59e0b",
    outputs: 1,
    defaultLabel: "Booking",
    defaultConfig: () => ({ slotsToShow: 6 }),
  },
  thank_you: {
    type: "thank_you",
    label: "Thank You",
    description: "Pagina di ringraziamento",
    icon: "💝",
    category: "conversion",
    color: "#fef3c7",
    borderColor: "#f59e0b",
    outputs: 1,
    isEndNode: true,
    defaultLabel: "Grazie",
    defaultConfig: () => ({ thankYouPageId: "" }),
  },
  chat_ai: {
    type: "chat_ai",
    label: "Chat AI",
    description: "Assistente conversazionale",
    icon: "🤖",
    category: "interaction",
    color: "#ede9fe",
    borderColor: "#8b5cf6",
    outputs: 1,
    defaultLabel: "Chat AI",
    defaultConfig: () => ({ chatBotId: "" }),
  },
  condition: {
    type: "condition",
    label: "Condizione",
    description: "Diramazione if/else",
    icon: "🔀",
    category: "logic",
    color: "#e0e7ff",
    borderColor: "#6366f1",
    outputs: 2,
    defaultLabel: "Condizione",
    defaultConfig: () => ({ rule: "tag", operator: "contains", value: "" }),
  },
  delay: {
    type: "delay",
    label: "Attesa",
    description: "Pausa temporale",
    icon: "⏱️",
    category: "logic",
    color: "#e0e7ff",
    borderColor: "#6366f1",
    outputs: 1,
    defaultLabel: "Attendi",
    defaultConfig: () => ({ amount: 1, unit: "hours" }),
  },
  action_email: {
    type: "action_email",
    label: "Invia Email",
    description: "Email automatica",
    icon: "✉️",
    category: "automation",
    color: "#fce7f3",
    borderColor: "#ec4899",
    outputs: 1,
    defaultLabel: "Email",
    defaultConfig: () => ({ to: "lead", templateId: "", subject: "" }),
  },
  action_tag: {
    type: "action_tag",
    label: "Aggiungi Tag",
    description: "Tag al lead",
    icon: "🏷️",
    category: "automation",
    color: "#fce7f3",
    borderColor: "#ec4899",
    outputs: 1,
    defaultLabel: "Tag",
    defaultConfig: () => ({ tags: [] }),
  },
  action_level: {
    type: "action_level",
    label: "Cambia Livello",
    description: "Aggiorna livello funnel",
    icon: "📊",
    category: "automation",
    color: "#fce7f3",
    borderColor: "#ec4899",
    outputs: 1,
    defaultLabel: "Livello",
    defaultConfig: () => ({ newLevel: "lead_caldo" }),
  },
  action_notify: {
    type: "action_notify",
    label: "Notifica Interna",
    description: "Email allo studio",
    icon: "🔔",
    category: "automation",
    color: "#fce7f3",
    borderColor: "#ec4899",
    outputs: 1,
    defaultLabel: "Notifica",
    defaultConfig: () => ({ recipient: "", subject: "" }),
  },
  action_webhook: {
    type: "action_webhook",
    label: "Webhook",
    description: "Chiama URL esterno",
    icon: "🔗",
    category: "automation",
    color: "#fce7f3",
    borderColor: "#ec4899",
    outputs: 1,
    defaultLabel: "Webhook",
    defaultConfig: () => ({ url: "", method: "POST" }),
  },
  exit: {
    type: "exit",
    label: "Fine",
    description: "Termina il funnel",
    icon: "🏁",
    category: "exit",
    color: "#f3f4f6",
    borderColor: "#6b7280",
    outputs: 0,
    isEndNode: true,
    defaultLabel: "Fine",
    defaultConfig: () => ({}),
  },
  redirect: {
    type: "redirect",
    label: "Redirect",
    description: "URL esterno",
    icon: "↗️",
    category: "exit",
    color: "#f3f4f6",
    borderColor: "#6b7280",
    outputs: 0,
    isEndNode: true,
    defaultLabel: "Redirect",
    defaultConfig: () => ({ url: "" }),
  },
};

export function createFlowNode(
  type: FlowNodeType,
  position: { x: number; y: number },
  overrides: Partial<FlowNode["data"]> = {}
): FlowNode {
  const def = FLOW_NODE_DEFINITIONS[type];
  return {
    id: `node_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
    type,
    position,
    data: {
      label: overrides.label || def.defaultLabel,
      description: overrides.description,
      config: { ...def.defaultConfig(), ...(overrides.config || {}) },
      ...overrides,
    },
  };
}
